CREATE TABLE [ods].[Emma_Contacts_Outbound_Json_Payload]
(
[accountID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmmaMemberID] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TicketLevelAccountRep] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountFirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountLastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryPhone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryEmail] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KidsClubMemberName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KidsClubMemberBirthday] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KidsClubMember2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KidsClubMemberirthday2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KidsClubMember3] [int] NULL,
[KidsClubMemberBirthday3] [int] NULL,
[Acct_ID] [bigint] NULL,
[SeasonTicketPriceCode] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH] [int] NULL,
[Founders_Flag] [int] NULL,
[AccountType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BrokerFlag] [int] NULL,
[Titans_True] [int] NULL,
[Kids_Club] [int] NULL,
[UpcomingGameFlag] [int] NULL,
[sectionname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatLocation] [nvarchar] (114) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NumberofSeats] [int] NULL,
[Club_Holder] [int] NULL,
[Upper_Bowl] [int] NULL,
[Lower_Bowl] [int] NULL,
[since_date] [datetime] NULL,
[SGB] [int] NULL,
[Group_Buyer] [int] NULL,
[Partial_Plan] [int] NULL,
[QueueID] [int] NOT NULL,
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[SecondaryEmail] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParkingFlag] [bit] NULL,
[seasonyear] [int] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
