CREATE TABLE [src].[Emma_Members]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberID] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedAt] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberStatusID] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlainTextPreferred] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberSince] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BounceCount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeletedAt] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBID] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyBusinessName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchticsAcctID] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhenIsTheBestTimeForUsToContactYou-] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetAddress] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentGuardianPhone] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CokeHOFPhotoshoot] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdditionalMember1_Birthday] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentGuardianFirstName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdditionalMember1_FirstName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentGuardianAddress] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentGuardianLastName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KidsClubMemberFirstName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KidsClubMemberBirthday] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdditionalComments] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdditionalMember2_Birthday] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdditionalMember2_FirstName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
